theme = "gruvbox_dark_hard"

[editor]
mouse = false
true-color = true
bufferline = 'always'
color-modes = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
